# =============================================================================
# FAPROTAX Analysis - Notufts Version (CORRECTED)
# Manuscript: AEM00316-26 - Lake Untersee cross-habitat microbial communities
# Tuft samples (filament 1-5) removed from all analyses
# Input: faprotax_output_notufts.tsv (generated by FAPROTAX 1.2.12)
# Color convention: Desiccated=#E31A1C, Pond=#1F78B4, Lake=#33A02C
# Environment order throughout: Desiccated -> Pond -> Lake
#
# FIXES APPLIED IN THIS VERSION:
#   1. plyr::summarise() masking dplyr::summarise() -> detach plyr + namespace
#      all dplyr verbs explicitly (group_by/summarise/arrange).
#   2. add_significance_testing(): tryCatch() success branch used `<-` instead
#      of `<<-`, so results never actually accumulated -> fixed scoping.
#   3. No multiple-testing correction across the ~35 functional groups tested
#      -> added Benjamini-Hochberg (BH) correction; significance stars and
#      highest_env now derived from p_adj, not raw p_value.
# =============================================================================

setwd("~/Desktop/Research_Projects/Lake_Untersee/Dry_mats/No tufts/no_tufts_16S/")

library(dplyr)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(vegan)
library(cowplot)

# Ensure dplyr's group_by/summarise/arrange are used, not plyr's --
# plyr, if loaded elsewhere in this R session, masks dplyr::summarise()
# and silently breaks grouped summaries (drops the grouping column).
if ("package:plyr" %in% search()) {
  detach("package:plyr", unload = TRUE)
}
if (!identical(environment(dplyr::summarise), environment(summarise))) {
  warning("summarise() is not resolving to dplyr -- check package load order / masking.")
}

# -----------------------------------------------------------------------------
# COLOR SCHEME AND ENVIRONMENT ORDER
# -----------------------------------------------------------------------------
env_order  <- c("Desiccated", "Pond", "Lake")
env_colors <- c("Desiccated" = "#E31A1C", "Pond" = "#1F78B4", "Lake" = "#33A02C")

# -----------------------------------------------------------------------------
# 1. LOAD DATA
# -----------------------------------------------------------------------------
cat("=== LOADING DATA ===\n")

faprotax_data <- read.table(
  "faprotax_output_notufts.tsv",
  sep             = "\t",
  header          = TRUE,
  row.names       = 1,
  stringsAsFactors = FALSE,
  check.names     = FALSE
)

metadata <- read.delim(
  "Drymats_metadata_final.txt",
  stringsAsFactors = FALSE
)

# Remove tuft samples from metadata (safety check)
tuft_samples <- c("filament 1", "filament 2", "filament 3", "filament 4", "filament 5")
metadata     <- metadata[!metadata$Sample %in% tuft_samples, ]

cat("FAPROTAX dimensions:", dim(faprotax_data), "\n")
cat("Metadata rows:", nrow(metadata), "\n")

# -----------------------------------------------------------------------------
# 2. NORMALIZATION
# -----------------------------------------------------------------------------
cat("\n=== NORMALIZING ===\n")

col_sums     <- colSums(faprotax_data)
faprotax_norm <- sweep(faprotax_data, 2, col_sums, "/")
faprotax_norm[is.na(faprotax_norm)] <- 0

cat("Normalization check - sample sum range:", range(colSums(faprotax_norm)), "\n")

# -----------------------------------------------------------------------------
# 3. MATCH SAMPLES WITH METADATA
# -----------------------------------------------------------------------------
cat("\n=== MATCHING SAMPLES ===\n")

common_samples   <- intersect(colnames(faprotax_norm), metadata$Sample)

if(length(common_samples) == 0) {
  # Try period-to-space conversion
  colnames(faprotax_norm) <- gsub("\\.", " ", colnames(faprotax_norm))
  common_samples <- intersect(colnames(faprotax_norm), metadata$Sample)
}

cat("Matched samples:", length(common_samples), "\n")
if(length(common_samples) == 0) stop("No samples matched. Check metadata Sample column names.")

faprotax_final   <- faprotax_norm[, common_samples, drop = FALSE]
metadata_matched <- metadata[metadata$Sample %in% common_samples, ]
metadata_matched <- metadata_matched[match(colnames(faprotax_final), metadata_matched$Sample), ]
metadata_matched$Environment <- factor(metadata_matched$Environment, levels = env_order)

cat("Final environment distribution:\n")
print(table(metadata_matched$Environment))

# Remove functions with all zeros
nonzero_rows  <- rowSums(faprotax_final) > 0
faprotax_final <- faprotax_final[nonzero_rows, ]
cat("Non-zero functional groups:", nrow(faprotax_final), "\n")

# -----------------------------------------------------------------------------
# CATEGORY FILTERS
# -----------------------------------------------------------------------------
# Excluded: database artifacts with no environmental ecological interpretation
artifact_categories <- c(
  "human_associated",           # Afipia + Roseomonas -- opportunistic clinical taxa
  "human_pathogens_all",        # same taxa -- not genuine environmental pathogens
  "animal_parasites_or_symbionts", # same taxa -- not bird-associated
  "human_pathogens_septicemia",
  "human_pathogens_pneumonia",
  "human_pathogens_nosocomia",
  "human_pathogens_meningitis",
  "human_pathogens_gastroenteritis",
  "human_pathogens_diarrhea",
  "fish_parasites",
  "plant_pathogen",
  "invertebrate_parasites",
  "mammal_gut",
  "human_gut",
  "intracellular_parasites"     # shown only in Panel C with ecological reframing
  # NOTE: predatory_or_exoparasitic is KEPT -- driven by Bdellovibrio and
  # Haliangium, both legitimate bacterial predators ecologically interpretable
  # in the stable lake environment context
)

# Excluded: redundant parent categories that are supersets of specific ones shown
redundant_categories <- c(
  "phototrophy",            # superset of photosynthetic_cyanobacteria
  "photoautotrophy",        # superset of photosynthetic_cyanobacteria
  "oxygenic_photoautotrophy", # superset of photosynthetic_cyanobacteria
  "chemoheterotrophy"       # superset of aerobic_chemoheterotrophy
)

# All excluded categories combined
excluded_categories <- c(artifact_categories, redundant_categories)

# intracellular_parasites is KEPT -- driven by Legionella, Coxiella, Neochlamydia,
# Candidatus Megaira, Candidatus Gigarickettsia, Candidatus Protochlamydia,
# Rickettsia -- all environmental amoeba-associated endosymbionts/parasites.
# Ecologically interpretable: reflects protist-bacteria intracellular interactions
# consistent with Hartmannella vermiformis (pond indicator) and Chlamydiae
# (lake indicator) in eukaryotic community analysis.

# -----------------------------------------------------------------------------
# 4. SIGNIFICANCE TESTING (CORRECTED: proper scoping + dplyr namespacing + BH)
# -----------------------------------------------------------------------------
add_significance_testing <- function(faprotax_matrix, metadata, functions_to_test) {

  results <- data.frame(
    Function = character(0), p_value = numeric(0),
    highest_env = character(0), stringsAsFactors = FALSE
  )

  for(func in functions_to_test) {
    sample_data <- data.frame()
    for(env in levels(metadata$Environment)) {
      env_samples <- metadata$Sample[metadata$Environment == env]
      env_samples <- intersect(env_samples, colnames(faprotax_matrix))
      if(length(env_samples) > 0) {
        sample_data <- rbind(sample_data, data.frame(
          Function    = func,
          Environment = env,
          Abundance   = as.numeric(faprotax_matrix[func, env_samples]),
          stringsAsFactors = FALSE
        ))
      }
    }

    if(nrow(sample_data) > 0 && length(unique(sample_data$Environment)) > 1) {
      kw <- tryCatch(kruskal.test(Abundance ~ Environment, data = sample_data),
                     error = function(e) NULL)
      if (!is.null(kw)) {
        p_value <- kw$p.value
        env_medians <- sample_data %>%
          dplyr::group_by(Environment) %>%
          dplyr::summarise(med = median(Abundance), .groups = "drop") %>%
          dplyr::arrange(dplyr::desc(med))
        highest_env <- as.character(env_medians$Environment[1])
        results <- rbind(results, data.frame(
          Function = func, p_value = p_value, highest_env = highest_env,
          stringsAsFactors = FALSE
        ))
      } else {
        results <- rbind(results, data.frame(
          Function = func, p_value = NA, highest_env = "", stringsAsFactors = FALSE
        ))
      }
    } else {
      results <- rbind(results, data.frame(
        Function = func, p_value = NA, highest_env = "", stringsAsFactors = FALSE
      ))
    }
  }

  # BH correction applied ONCE across all functions tested in this call
  results$p_adj <- p.adjust(results$p_value, method = "BH")
  results$significance <- ""
  results$significance[!is.na(results$p_adj) & results$p_adj < 0.001] <- "***"
  results$significance[!is.na(results$p_adj) & results$p_adj >= 0.001 & results$p_adj < 0.01] <- "**"
  results$significance[!is.na(results$p_adj) & results$p_adj >= 0.01 & results$p_adj < 0.05] <- "*"

  return(results)
}

# -----------------------------------------------------------------------------
# 5. HELPER: BUILD PLOT DATA WITH STATS (dplyr:: namespaced)
# -----------------------------------------------------------------------------
build_plot_data <- function(faprotax_matrix, metadata, functions_list) {

  func_env_means <- data.frame()
  for(env in levels(metadata$Environment)) {
    env_samples <- metadata$Sample[metadata$Environment == env]
    env_samples <- intersect(env_samples, colnames(faprotax_matrix))
    if(length(env_samples) > 0) {
      env_means <- rowMeans(faprotax_matrix[functions_list, env_samples, drop = FALSE])
      func_env_means <- rbind(func_env_means, data.frame(
        Function       = names(env_means),
        Mean_Abundance = env_means,
        Environment    = factor(env, levels = env_order),
        stringsAsFactors = FALSE
      ))
    }
  }

  avg_abund <- func_env_means %>%
    dplyr::group_by(Function) %>%
    dplyr::summarise(Overall_Mean = mean(Mean_Abundance), .groups = "drop")

  plot_data <- func_env_means %>%
    dplyr::left_join(avg_abund, by = "Function")

  sig_results <- add_significance_testing(faprotax_matrix, metadata, functions_list)
  if(nrow(sig_results) > 0) {
    plot_data <- plot_data %>% dplyr::left_join(sig_results, by = "Function")
  } else {
    plot_data <- plot_data %>%
      dplyr::mutate(p_value = NA_real_, significance = "", highest_env = "")
  }

  max_abund <- plot_data %>%
    dplyr::group_by(Function) %>%
    dplyr::summarise(max_val = max(Mean_Abundance), .groups = "drop")

  plot_data %>% dplyr::left_join(max_abund, by = "Function")
}

# Helper to add significance labels to a bar plot
# Labels are placed just to the right of the longest bar in each group
# hjust = 0 means label starts at the anchor point, extending rightward
add_sig_labels <- function(p, plot_data) {
  sig_data <- plot_data %>%
    dplyr::filter(!is.na(significance) & significance != "") %>%
    dplyr::group_by(Function) %>%
    dplyr::slice_head(n = 1) %>%
    dplyr::mutate(label = paste0(significance, " (", substring(highest_env, 1, 1), ")"))

  if(nrow(sig_data) > 0) {
    p <- p + geom_text(
      data        = sig_data,
      aes(x = reorder(Function, Overall_Mean), y = max_val * 1.03, label = label),
      inherit.aes = FALSE,
      hjust       = 0,
      size        = 3.5,
      fontface    = "bold",
      color       = "black"
    )
  }
  return(p)
}

# -----------------------------------------------------------------------------
# PLOT A: FUNCTIONAL ORDINATION (PCoA - Bray-Curtis)
# -----------------------------------------------------------------------------
create_ordination_plot <- function(faprotax_matrix, metadata) {
  func_t        <- t(faprotax_matrix)
  func_dist     <- vegdist(func_t, method = "bray")
  pcoa_result   <- cmdscale(func_dist, eig = TRUE, k = 2)
  var_explained <- pcoa_result$eig / sum(abs(pcoa_result$eig)) * 100

  pcoa_df <- data.frame(
    Sample      = rownames(func_t),
    PC1         = pcoa_result$points[, 1],
    PC2         = pcoa_result$points[, 2],
    Environment = factor(
      metadata$Environment[match(rownames(func_t), metadata$Sample)],
      levels = env_order
    )
  )

  ggplot(pcoa_df, aes(x = PC1, y = PC2, color = Environment)) +
    geom_point(size = 3, alpha = 0.8) +
    stat_ellipse(level = 0.95, linewidth = 1) +
    scale_color_manual(values = env_colors) +
    theme_minimal(base_size = 11) +
    labs(
      title    = "Functional Profile Ordination (PCoA)",
      subtitle = "Bray-Curtis dissimilarity of FAPROTAX functions",
      x        = paste0("PC1 (", round(var_explained[1], 1), "%)"),
      y        = paste0("PC2 (", round(var_explained[2], 1), "%)")
    ) +
    theme(
      plot.title      = element_text(hjust = 0.5, size = 12, face = "bold"),
      plot.subtitle   = element_text(hjust = 0.5, size = 9),
      axis.text       = element_text(size = 10),
      legend.position = "none"
    )
}

# -----------------------------------------------------------------------------
# PLOT B: DOMINANT METABOLIC STRATEGIES
# Shows the most abundant ecologically interpretable functional categories
# Explicitly defined list -- no biogeochemical cycling functions (those go to C)
# No overlap with Panel C
# -----------------------------------------------------------------------------
create_top_functions_plot <- function(faprotax_matrix, metadata, n = 15) {

  panel_B_exclude <- c(
    excluded_categories,
    "nitrification", "aerobic_ammonia_oxidation", "methylotrophy",
    "methanol_oxidation", "manganese_oxidation", "chitinolysis",
    "nitrogen_fixation", "dark_hydrogen_oxidation", "ureolysis",
    "fermentation", "cellulolysis", "aromatic_compound_degradation",
    "dark_sulfide_oxidation", "sulfate_respiration", "sulfur_respiration",
    "methanotrophy", "acetoclastic_methanogenesis", "methanogenesis",
    "dark_thiosulfate_oxidation", "dark_sulfur_oxidation",
    "aerobic_nitrite_oxidation", "nitrate_denitrification",
    "nitrite_denitrification", "denitrification", "anammox",
    "nitrate_ammonification", "reductive_acetogenesis"
  )

  panel_B_explicit <- c(
    "photosynthetic_cyanobacteria",
    "aerobic_chemoheterotrophy",
    "photoheterotrophy",
    "predatory_or_exoparasitic",
    "nitrate_reduction"
  )

  top_functions <- panel_B_explicit[panel_B_explicit %in% rownames(faprotax_matrix)]
  top_functions <- top_functions[rowSums(faprotax_matrix[top_functions, , drop = FALSE]) > 0]

  plot_data <- build_plot_data(faprotax_matrix, metadata, top_functions)
  plot_data$Environment <- factor(plot_data$Environment, levels = rev(env_order))

  p <- ggplot(plot_data,
              aes(x = reorder(Function, Overall_Mean),
                  y = Mean_Abundance, fill = Environment)) +
    geom_col(position = "dodge", alpha = 0.8, width = 0.6) +
    scale_fill_manual(values = env_colors, breaks = env_order) +
    coord_flip() +
    theme_minimal(base_size = 11) +
    labs(
      title    = "Dominant Functional Categories",
      subtitle = "Mean relative abundance (BH-adjusted:\n*p<0.05, **p<0.01, ***p<0.001; D=Desiccated, P=Pond, L=Lake)",
      x        = NULL,
      y        = "Mean Relative Abundance"
    ) +
    theme(
      plot.title      = element_text(hjust = 0.5, size = 12, face = "bold"),
      plot.subtitle   = element_text(hjust = 0.5, size = 9),
      axis.text.y     = element_text(size = 9),
      axis.text.x     = element_text(size = 9),
      legend.position = "none",
      # Compensate for Panel D's facet strip band (from facet_wrap), which
      # Panel B has no equivalent of -- this extra top margin approximates
      # that strip's height so both plots' overall height (and tag position)
      # line up when stacked in the same patchwork column
      plot.margin       = margin(t = 20, r = 5.5, b = 5.5, l = 5.5),
      # Nudge the "B" tag rightward to match "D"'s horizontal position
      # (x=0 is far left, x=1 is far right) -- adjust this value up/down
      # after visually checking alignment
      plot.tag.position = c(0.03, 0.99)
    )

  add_sig_labels(p, plot_data)
}

# -----------------------------------------------------------------------------
# PLOT C: SIGNIFICANTLY DIFFERENT BIOGEOCHEMICAL CYCLING FUNCTIONS
# -----------------------------------------------------------------------------
create_biogeochem_plot <- function(faprotax_matrix, metadata) {

  significant_biogeochem <- c(
    "intracellular_parasites",
    "fermentation",
    "dark_hydrogen_oxidation",
    "nitrification",
    "manganese_oxidation",
    "aerobic_ammonia_oxidation",
    "chitinolysis",
    "methylotrophy",
    "methanol_oxidation",
    "nitrogen_fixation"
  )

  available <- significant_biogeochem[
    significant_biogeochem %in% rownames(faprotax_matrix)
  ]
  available <- available[
    rowSums(faprotax_matrix[available, , drop = FALSE]) > 0
  ]

  if(length(available) == 0) {
    return(ggplot() +
           annotate("text", x = 0.5, y = 0.5,
                    label = "No significant biogeochemical functions found") +
           theme_void())
  }

  plot_data <- build_plot_data(faprotax_matrix, metadata, available)
  plot_data$Environment <- factor(plot_data$Environment, levels = rev(env_order))

  sig_data_C <- plot_data %>%
    dplyr::filter(!is.na(significance) & significance != "") %>%
    dplyr::group_by(Function) %>%
    dplyr::slice_head(n = 1) %>%
    dplyr::mutate(label = paste0(significance, " (", substring(highest_env, 1, 1), ")"))

  p <- ggplot(plot_data,
              aes(x = reorder(Function, Overall_Mean),
                  y = Mean_Abundance, fill = Environment)) +
    geom_col(position = "dodge", alpha = 0.8, width = 0.6) +
    scale_fill_manual(values = env_colors, breaks = env_order) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.18))) +
    coord_flip() +
    theme_minimal(base_size = 11) +
    labs(
      title    = "Biogeochemical Cycling Functions",
      subtitle = "Significantly different among habitats (BH-adjusted:\n*p<0.05, **p<0.01, ***p<0.001; D=Desiccated, P=Pond, L=Lake)",
      x        = NULL,
      y        = "Mean Relative Abundance"
    ) +
    theme(
      plot.title      = element_text(hjust = 0.5, size = 12, face = "bold"),
      plot.subtitle   = element_text(hjust = 0.5, size = 9),
      axis.text.y     = element_text(size = 9),
      axis.text.x     = element_text(size = 9),
      legend.position = "none"
    )

  if(nrow(sig_data_C) > 0) {
    sig_data_C_main <- sig_data_C[sig_data_C$Function != "intracellular_parasites", ]
    sig_data_C_ip   <- sig_data_C[sig_data_C$Function == "intracellular_parasites", ]

    p <- p + geom_text(
      data        = sig_data_C_main,
      aes(x = reorder(Function, Overall_Mean), y = max_val * 1.03, label = label),
      inherit.aes = FALSE,
      hjust       = 0,
      size        = 3.5,
      fontface    = "bold",
      color       = "black"
    )

    if (nrow(sig_data_C_ip) > 0) {
      p <- p + geom_text(
        data        = sig_data_C_ip,
        aes(x = reorder(Function, Overall_Mean), y = max_val * 1.03, label = label),
        inherit.aes = FALSE,
        hjust       = 0,
        size        = 3.5,
        fontface    = "bold",
        color       = "black"
      )
    }
  }

  return(p)
}

# -----------------------------------------------------------------------------
# PLOT D_SUPP: TAXA DRIVING BIOGEOCHEMICAL FUNCTIONS (dplyr:: namespaced)
# -----------------------------------------------------------------------------
create_biogeochem_taxa_plot <- function(faprotax_matrix, metadata) {

  taxa_function_df <- data.frame(
    Function = c(
      rep("fermentation", 7),
      rep("nitrification", 6),
      rep("intracellular_parasites", 7),
      rep("dark_hydrogen_oxidation", 1),
      rep("manganese_oxidation", 1),
      rep("methylotrophy", 2),
      rep("chitinolysis", 1),
      rep("nitrogen_fixation", 3),
      rep("cellulolysis", 2),
      rep("ureolysis", 3),
      rep("aromatic_compound_degradation", 2),
      rep("dark_sulfide_oxidation", 1)
    ),
    Genus = c(
      "Truepera", "Sporolactobacillus", "Carnobacterium",
      "Acetoanaerobium", "Anaerovorax", "Rhodoferax", "Opitutus",
      "Nitrosomonas", "Nitrosospira", "Ellin6067", "MND1",
      "Candidatus_Nitrotoga", "966-1",
      "Legionella", "Coxiella", "Rickettsia",
      "Candidatus_Megaira", "Candidatus_Gigarickettsia", "Neochlamydia", "Candidatus_Protochlamydia",
      "Hydrogenophaga",
      "Leptothrix",
      "Methylotenera", "Methylobacter",
      "Lysobacter",
      "Nostoc_PCC-73102", "Mesorhizobium", "Bradyrhizobium",
      "Cytophaga", "Sporocytophaga",
      "Roseomonas", "Mesorhizobium", "Aminobacter",
      "Rhodococcus", "Nocardioides",
      "Thiobacillus"
    ),
    stringsAsFactors = FALSE
  ) %>% dplyr::distinct()

  biogeochem_funcs <- unique(taxa_function_df$Function)
  func_list        <- biogeochem_funcs[biogeochem_funcs %in% rownames(faprotax_matrix)]

  # NOTE: genus-level values must come from the raw ASV table + taxonomy,
  # not from the function-level FAPROTAX matrix (which has no genus
  # resolution) -- using the FAPROTAX mean directly here would repeat the
  # SAME function-level value across every genus row, making all genera
  # within a function appear identical regardless of their true abundance.
  .input_notufts_bg <- readRDS("bac_input_filt_rare_notufts.rds")
  .asv_table_bg <- .input_notufts_bg$data_loaded
  .tax_table_bg <- .input_notufts_bg$taxonomy_loaded
  .rel_asv_bg   <- sweep(.asv_table_bg, 2, colSums(.asv_table_bg), "/")

  plot_data <- data.frame()
  for (env in levels(metadata$Environment)) {
    env_samples <- metadata$Sample[metadata$Environment == env]
    env_samples <- intersect(env_samples, colnames(.rel_asv_bg))
    if (length(env_samples) == 0) next

    df_sub <- taxa_function_df %>% dplyr::filter(Function %in% func_list) %>% dplyr::distinct()

    for (i in seq_len(nrow(df_sub))) {
      func  <- df_sub$Function[i]
      genus <- df_sub$Genus[i]
      matching <- .tax_table_bg$taxonomy6 == genus
      genus_abund <- if (sum(matching) > 0) {
        mean(colSums(.rel_asv_bg[matching, env_samples, drop = FALSE]))
      } else 0

      plot_data <- rbind(plot_data, data.frame(
        Function = func, Genus = genus,
        Environment = factor(env, levels = env_order),
        Mean_Abundance = genus_abund,
        stringsAsFactors = FALSE
      ))
    }
  }

  min_threshold <- 0.003
  genera_to_keep <- plot_data %>%
    dplyr::group_by(Genus) %>%
    dplyr::summarise(max_abund = max(Mean_Abundance), .groups = "drop") %>%
    dplyr::filter(max_abund >= min_threshold) %>%
    dplyr::pull(Genus)

  plot_data <- plot_data %>% dplyr::filter(Genus %in% genera_to_keep)

  cat("Genera retained after threshold filter (>= ", min_threshold, "):",
      length(genera_to_keep), "\n")

  all_genera  <- sort(unique(plot_data$Genus))
  all_funcs   <- levels(factor(plot_data$Function))

  full_grid <- expand.grid(
    Genus       = all_genera,
    Function    = unique(plot_data$Function),
    Environment = factor(env_order, levels = env_order),
    stringsAsFactors = FALSE
  )

  plot_data <- full_grid %>%
    dplyr::left_join(plot_data, by = c("Genus", "Function", "Environment")) %>%
    dplyr::mutate(Mean_Abundance = ifelse(is.na(Mean_Abundance), 0, Mean_Abundance))

  func_order <- plot_data %>%
    dplyr::group_by(Function) %>%
    dplyr::summarise(total = sum(Mean_Abundance), .groups = "drop") %>%
    dplyr::arrange(total) %>%
    dplyr::pull(Function)

  genus_order <- all_genera

  plot_data$Function    <- factor(plot_data$Function,    levels = func_order)
  plot_data$Genus       <- factor(plot_data$Genus,       levels = genus_order)
  plot_data$Environment <- factor(plot_data$Environment, levels = env_order)

  global_max <- max(plot_data$Mean_Abundance, na.rm = TRUE)

  make_env_heatmap <- function(env_name, fill_high, show_y = TRUE) {
    env_data <- plot_data %>%
      dplyr::filter(Environment == env_name) %>%
      dplyr::mutate(Plot_Abundance = ifelse(Mean_Abundance > 0, Mean_Abundance, NA_real_))

    p <- ggplot(env_data, aes(x = Genus, y = Function, fill = Plot_Abundance)) +
      geom_tile(color = "grey85", linewidth = 0.3) +
      scale_fill_gradient(
        low      = "white",
        high     = fill_high,
        na.value = "white",
        name     = "Mean relative\nabundance",
        limits   = c(0, global_max)
      ) +
      scale_x_discrete(limits = genus_order) +
      theme_minimal(base_size = 9) +
      labs(title = env_name, x = NULL, y = NULL) +
      theme(
        plot.title      = element_text(hjust = 0.5, size = 10, face = "bold",
                                        color = fill_high),
        axis.text.x     = element_text(angle = 45, hjust = 1, size = 7,
                                        face = "italic"),
        axis.text.y     = if(show_y) element_text(size = 7.5) else element_blank(),
        panel.grid      = element_blank(),
        legend.position = "right"
      )
    return(p)
  }

  p_desic <- make_env_heatmap("Desiccated", env_colors["Desiccated"], show_y = TRUE)
  p_pond  <- make_env_heatmap("Pond",        env_colors["Pond"],        show_y = FALSE)
  p_lake  <- make_env_heatmap("Lake",        env_colors["Lake"],        show_y = FALSE)

  (p_desic | p_pond | p_lake) +
    plot_annotation(
      title   = "Taxa Driving Biogeochemical Functions",
      caption = "White = absent or unassigned  |  intracellular_parasites = amoeba-associated endosymbionts",
      theme   = theme(
        plot.title   = element_text(face = "bold", size = 11, hjust = 0.5),
        plot.caption = element_text(size = 7, hjust = 0.5)
      )
    ) &
    theme(text = element_text(family = "sans", face = "bold"))
}

# -----------------------------------------------------------------------------
# PLOT D: FUNCTIONAL DIVERSITY
# -----------------------------------------------------------------------------
create_diversity_plot <- function(faprotax_matrix, metadata) {
  diversity_results <- data.frame()
  for(env in levels(metadata$Environment)) {
    env_samples <- metadata$Sample[metadata$Environment == env]
    env_samples <- intersect(env_samples, colnames(faprotax_matrix))
    if(length(env_samples) > 0) {
      for(sample in env_samples) {
        abundances <- faprotax_matrix[, sample]
        abundances <- abundances[abundances > 0]
        if(length(abundances) > 1) {
          props    <- abundances / sum(abundances)
          shannon  <- -sum(props * log(props))
          richness <- length(abundances)
          evenness <- shannon / log(richness)
          diversity_results <- rbind(diversity_results, data.frame(
            Sample      = sample,
            Environment = factor(env, levels = env_order),
            Richness    = richness,
            Evenness    = evenness
          ))
        }
      }
    }
  }

  div_long <- diversity_results %>%
    tidyr::pivot_longer(c(Richness, Evenness), names_to = "Metric", values_to = "Value")

  # Explicitly order facets Richness first, then Evenness (facet_wrap
  # defaults to alphabetical, which would put Evenness first)
  div_long$Metric <- factor(div_long$Metric, levels = c("Richness", "Evenness"))

  # Pairwise letters (Dunn's test) -- only for Richness, since its omnibus
  # Kruskal-Wallis is significant (p = 0.007); Evenness's omnibus test is
  # not significant (p = 0.213), so pairwise letters there would be
  # uninformative (all groups would receive the same letter)
  kw_rich <- kruskal.test(Richness ~ Environment, data = diversity_results)

  richness_letters <- NULL
  if (kw_rich$p.value < 0.05) {
    dunn_rich <- FSA::dunnTest(Richness ~ Environment, data = diversity_results, method = "bh")
    cld <- multcompView::multcompLetters(setNames(dunn_rich$res$P.adj,
                                                   gsub(" ", "", dunn_rich$res$Comparison)))$Letters
    richness_letters <- data.frame(Environment = names(cld), Letter = as.character(cld),
                                   Metric = factor("Richness", levels = c("Richness", "Evenness")),
                                   stringsAsFactors = FALSE)
    richness_letters$Environment <- factor(richness_letters$Environment, levels = env_order)
    richness_letters$y_pos <- max(diversity_results$Richness) * 1.08
  }

  p_div <- ggplot(div_long, aes(x = Environment, y = Value, fill = Environment)) +
    geom_boxplot(alpha = 0.7, outlier.shape = NA) +
    geom_jitter(width = 0.2, size = 1.5, alpha = 0.6) +
    facet_wrap(~Metric, scales = "free_y", ncol = 2) +
    scale_fill_manual(values = env_colors) +
    scale_x_discrete(limits = env_order) +
    theme_minimal(base_size = 11) +
    labs(
      title    = "Functional Diversity",
      subtitle = "Richness and Pielou evenness\nacross habitats",
      x        = NULL,
      y        = "Value"
    ) +
    theme(
      plot.title      = element_text(hjust = 0.5, size = 12, face = "bold"),
      plot.subtitle   = element_text(hjust = 0.5, size = 9),
      axis.text.x     = element_text(angle = 45, hjust = 1, size = 10),
      axis.text.y     = element_text(size = 10),
      strip.text      = element_text(size = 10, face = "bold"),
      legend.position = "none"
    )

  if (!is.null(richness_letters)) {
    p_div <- p_div + geom_text(
      data        = richness_letters,
      aes(x = Environment, y = y_pos, label = Letter),
      inherit.aes = FALSE,
      size        = 5,
      fontface    = "bold"
    )
  }

  p_div
}

# -----------------------------------------------------------------------------
# PLOT E: TAXA DRIVING KEY FUNCTIONS -- TWO PANEL VERSION (dplyr:: namespaced)
# -----------------------------------------------------------------------------
create_taxa_function_plot <- function(faprotax_matrix, metadata) {

  taxa_function_df <- data.frame(
    Function = c(
      rep("photosynthetic_cyanobacteria", 8),
      rep("intracellular_parasites", 7),
      rep("nitrification", 6),
      rep("nitrogen_fixation", 3),
      rep("manganese_oxidation", 1),
      rep("cellulolysis", 2),
      rep("dark_hydrogen_oxidation", 1),
      rep("fermentation", 7),
      rep("methylotrophy", 2),
      rep("chitinolysis", 1),
      rep("dark_sulfide_oxidation", 1),
      rep("ureolysis", 3),
      rep("aromatic_compound_degradation", 2),
      rep("aerobic_chemoheterotrophy", 8)
    ),
    Genus = c(
      "Tychonema_CCAP_1459-11B", "Leptolyngbya_ANT.L67.1", "Phormidium_CYN64", "Geitlerinema_LD9",
      "Chamaesiphon_PCC-7430", "Nostoc_PCC-73102", "Pseudanabaena_PCC-7429", "Nodosilinea_PCC-7104",
      "Legionella", "Coxiella", "Rickettsia", "Candidatus_Megaira",
      "Candidatus_Gigarickettsia", "Neochlamydia", "Candidatus_Protochlamydia",
      "Nitrosomonas", "Nitrosospira", "Ellin6067", "MND1",
      "Candidatus_Nitrotoga", "966-1",
      "Nostoc_PCC-73102", "Mesorhizobium", "Bradyrhizobium",
      "Leptothrix",
      "Cytophaga", "Sporocytophaga",
      "Hydrogenophaga",
      "Truepera", "Sporolactobacillus", "Carnobacterium",
      "Acetoanaerobium", "Anaerovorax", "Rhodoferax", "Opitutus",
      "Methylotenera", "Methylobacter",
      "Lysobacter",
      "Thiobacillus",
      "Roseomonas", "Mesorhizobium", "Aminobacter",
      "Rhodococcus", "Nocardioides",
      "Cryobacterium", "Flavobacterium", "Pedobacter",
      "Sphingomonas", "Rhodanobacter", "Nocardioides",
      "Bryobacter", "Galbitalea"
    ),
    stringsAsFactors = FALSE
  ) %>% dplyr::distinct()

  dominant_funcs <- c("photosynthetic_cyanobacteria", "aerobic_chemoheterotrophy")
  biogeochem_funcs <- c(
    "intracellular_parasites", "nitrification", "nitrogen_fixation",
    "manganese_oxidation", "cellulolysis", "dark_hydrogen_oxidation",
    "fermentation", "methylotrophy", "chitinolysis", "dark_sulfide_oxidation",
    "ureolysis", "aromatic_compound_degradation"
  )

  # Genus-level values must come from the raw ASV table + taxonomy, not
  # from the function-level FAPROTAX matrix -- see note in
  # create_biogeochem_taxa_plot() above for why the previous approach
  # (repeating one function-level value across every genus) was incorrect.
  .input_notufts_tf <- readRDS("bac_input_filt_rare_notufts.rds")
  .asv_table_tf <- .input_notufts_tf$data_loaded
  .tax_table_tf <- .input_notufts_tf$taxonomy_loaded
  .rel_asv_tf   <- sweep(.asv_table_tf, 2, colSums(.asv_table_tf), "/")

  build_taxa_plot_data <- function(func_set) {
    func_list <- func_set[func_set %in% rownames(faprotax_matrix)]
    df_sub    <- taxa_function_df %>% dplyr::filter(Function %in% func_list) %>% dplyr::distinct()

    result <- data.frame()
    for (env in levels(metadata$Environment)) {
      env_samples <- metadata$Sample[metadata$Environment == env]
      env_samples <- intersect(env_samples, colnames(.rel_asv_tf))
      if (length(env_samples) == 0) next

      for (i in seq_len(nrow(df_sub))) {
        func  <- df_sub$Function[i]
        genus <- df_sub$Genus[i]
        matching <- .tax_table_tf$taxonomy6 == genus
        genus_abund <- if (sum(matching) > 0) {
          mean(colSums(.rel_asv_tf[matching, env_samples, drop = FALSE]))
        } else 0

        result <- rbind(result, data.frame(
          Function = func, Genus = genus,
          Environment = factor(env, levels = env_order),
          Mean_Abundance = genus_abund,
          stringsAsFactors = FALSE
        ))
      }
    }
    result
  }

  build_three_panel_heatmap <- function(plot_data, panel_title, tile_height = 1, legend_horizontal = FALSE) {
    func_order <- plot_data %>%
      dplyr::group_by(Function) %>%
      dplyr::summarise(total = sum(Mean_Abundance), .groups = "drop") %>%
      dplyr::arrange(total) %>%
      dplyr::pull(Function)

    genus_order <- sort(unique(plot_data$Genus))

    plot_data$Function    <- factor(plot_data$Function,    levels = func_order)
    plot_data$Genus       <- factor(plot_data$Genus,       levels = genus_order)
    plot_data$Environment <- factor(plot_data$Environment, levels = env_order)

    global_max <- max(plot_data$Mean_Abundance, na.rm = TRUE)

    make_env_heatmap <- function(env_name, fill_high, show_y = TRUE) {
      env_data <- plot_data %>%
        dplyr::filter(Environment == env_name) %>%
        dplyr::mutate(Plot_Abundance = ifelse(Mean_Abundance > 0, Mean_Abundance, NA_real_))

      ggplot(env_data, aes(x = Genus, y = Function, fill = Plot_Abundance)) +
        geom_tile(color = "grey85", linewidth = 0.3, height = tile_height) +
        scale_fill_gradient(
          low      = "white",
          high     = fill_high,
          na.value = "white",
          name     = paste0(env_name, "\nMean relative\nabundance"),
          limits   = c(0, global_max)
        ) +
        theme_minimal(base_size = 10) +
        labs(title = env_name, x = NULL, y = NULL) +
        theme(
          plot.title      = element_text(hjust = 0.5, size = 11, face = "bold",
                                          color = fill_high),
          axis.text.x     = element_text(angle = 45, hjust = 1, size = 7.5,
                                          face = "bold.italic"),
          axis.text.y     = element_text(
                              size   = 8,
                              face   = "bold",
                              color  = if(show_y) "black" else "white"
                            ),
          panel.grid      = element_blank(),
          legend.position = "none"
        )
    }

    make_legend_plot <- function(env_name, fill_high) {
      env_data <- plot_data %>% dplyr::filter(Environment == env_name) %>%
        dplyr::mutate(Plot_Abundance = ifelse(Mean_Abundance > 0, Mean_Abundance, NA_real_))

      p <- ggplot(env_data, aes(x = Genus, y = Function, fill = Plot_Abundance)) +
        geom_tile() +
        scale_fill_gradient(
          low      = "white",
          high     = fill_high,
          na.value = "white",
          name     = paste0(env_name, "\nMean relative\nabundance"),
          limits   = c(0, global_max),
          breaks   = scales::breaks_pretty(n = 3),
          labels   = scales::label_number(accuracy = 0.01)
        ) +
        theme_minimal() +
        theme(
          legend.position   = "right",
          legend.title      = element_text(face = "bold", size = 8, color = fill_high),
          legend.text       = element_text(face = "bold", size = 7),
          legend.key.height = unit(0.35, "cm"),
          legend.key.width  = unit(0.35, "cm")
        )
      cowplot::get_legend(p)
    }

    p_desic <- make_env_heatmap("Desiccated", env_colors["Desiccated"], show_y = TRUE)
    p_pond  <- make_env_heatmap("Pond",        env_colors["Pond"],        show_y = FALSE)
    p_lake  <- make_env_heatmap("Lake",        env_colors["Lake"],        show_y = FALSE)

    leg_desic <- make_legend_plot("Desiccated", env_colors["Desiccated"])
    leg_pond  <- make_legend_plot("Pond",        env_colors["Pond"])
    leg_lake  <- make_legend_plot("Lake",        env_colors["Lake"])

    legends <- cowplot::plot_grid(leg_desic, leg_pond, leg_lake,
                                  ncol = if (legend_horizontal) 1 else 1,
                                  nrow = if (legend_horizontal) 3 else 3)

    panels <- cowplot::plot_grid(p_desic, p_pond, p_lake,
                                 ncol = 3, nrow = 1,
                                 rel_widths = c(1, 1, 1))

    full_plot <- cowplot::plot_grid(panels, legends,
                                    ncol = 2, nrow = 1,
                                    rel_widths = c(0.85, 0.15))

    cowplot::plot_grid(
      cowplot::ggdraw() +
        cowplot::draw_label(panel_title, fontface = "bold", size = 11, y = 0.15),
      full_plot,
      ncol = 1, nrow = 2,
      rel_heights = c(0.05, 0.95)
    )
  }

  # Each dominant function now gets its OWN independently-scaled heatmap
  # (separate global_max per function), rather than sharing one combined
  # colour scale -- this avoids the lower-abundance function's bars being
  # visually compressed/washed out by the higher-abundance function's range
  data_cyano  <- build_taxa_plot_data("photosynthetic_cyanobacteria")
  panel_cyano <- build_three_panel_heatmap(
    data_cyano,
    "A -- Photosynthetic Cyanobacteria",
    tile_height = 0.95
  )

  data_chemo  <- build_taxa_plot_data("aerobic_chemoheterotrophy")
  panel_chemo <- build_three_panel_heatmap(
    data_chemo,
    "B -- Aerobic Chemoheterotrophy",
    tile_height = 0.95
  )

  data_B  <- build_taxa_plot_data(biogeochem_funcs)
  panel_B <- build_three_panel_heatmap(
    data_B,
    "C -- Biogeochemical Cycling Functions",
    tile_height = 1
  )

  (panel_cyano / panel_chemo / panel_B) +
    plot_layout(heights = c(0.7, 0.7, 1)) +
    plot_annotation(
      title   = "Key Taxa Driving Functional Groups",
      caption = paste0("Fill intensity = mean relative abundance of functional group  |  ",
                       "White = taxon absent or not assigned to function in this habitat"),
      theme   = theme(
        plot.title   = element_text(face = "bold", size = 13, hjust = 0.5),
        plot.caption = element_text(size = 8, hjust = 0.5)
      )
    ) &
    theme(text = element_text(family = "sans", face = "bold"))
}

# -----------------------------------------------------------------------------
# 6. GENERATE ALL PLOTS
# -----------------------------------------------------------------------------
cat("\n=== GENERATING PLOTS ===\n")

plot_A <- create_ordination_plot(faprotax_final, metadata_matched)
cat("Plot A (ordination) done\n")

plot_B <- create_top_functions_plot(faprotax_final, metadata_matched, n = 15)
cat("Plot B (top 15 functions) done\n")

plot_C <- create_biogeochem_plot(faprotax_final, metadata_matched)
cat("Plot C (biogeochemical functions) done\n")

plot_D <- create_diversity_plot(faprotax_final, metadata_matched)
cat("Plot D (functional diversity) done\n")

plot_E <- create_taxa_function_plot(faprotax_final, metadata_matched)
cat("Plot E (full taxa-function heatmap -- supplementary) done\n")

plot_E_supp <- create_biogeochem_taxa_plot(faprotax_final, metadata_matched)
cat("Plot E_supp (taxa driving biogeochemical functions -- supplementary) done\n")

# -----------------------------------------------------------------------------
# 7. SAVE FIGURES
# -----------------------------------------------------------------------------
cat("\nSaving main 4-panel figure...\n")
combined_4panel <- (plot_A + plot_B) / (plot_C + plot_D) +
  plot_annotation(tag_levels = list(c("A", "B", "C", "D"))) &
  theme(legend.position = "bottom",
        plot.tag = element_text(size = 14, face = "bold"),
        text     = element_text(family = "sans", face = "bold"))

final_4panel <- combined_4panel

ggsave(
  "faprotax_4panel_notufts.pdf",
  final_4panel,
  width  = 16,
  height = 12,
  dpi    = 300
)
ggsave(
  "faprotax_4panel_notufts.jpeg",
  final_4panel,
  width   = 16,
  height  = 12,
  dpi     = 300,
  quality = 100
)
cat("Saved: faprotax_4panel_notufts.pdf and .jpeg\n")

cat("Saving taxa driving biogeochemical functions (supplementary)...\n")
ggsave(
  "faprotax_biogeochem_taxa_supp_notufts.pdf",
  plot_E_supp,
  width  = 18,
  height = 8,
  dpi    = 300
)
ggsave(
  "faprotax_biogeochem_taxa_supp_notufts.jpeg",
  plot_E_supp,
  width   = 18,
  height  = 8,
  dpi     = 300,
  quality = 100
)
cat("Saved: faprotax_biogeochem_taxa_supp_notufts.pdf and .jpeg\n")

cat("Saving full taxa-function heatmap (supplementary)...\n")
pdf("faprotax_taxa_functions_notufts.pdf", width = 26, height = 14)
print(plot_E)
dev.off()

jpeg("faprotax_taxa_functions_notufts.jpeg", width = 26, height = 14,
     units = "in", res = 300, quality = 100)
print(plot_E)
dev.off()

cat("Saved: faprotax_taxa_functions_notufts.pdf and .jpeg\n")

# -----------------------------------------------------------------------------
# 8. SUMMARY STATISTICS
# -----------------------------------------------------------------------------
cat("\n=== SUMMARY STATISTICS ===\n")

func_t    <- t(faprotax_final)
func_dist <- vegdist(func_t, method = "bray")
perm_result <- adonis2(
  func_dist ~ metadata_matched$Environment,
  permutations = 999
)
cat("\nPERMANOVA on functional profiles:\n")
print(perm_result)

dispersion <- betadisper(func_dist, metadata_matched$Environment)
perm_disp  <- permutest(dispersion, permutations = 999)
cat("\nPERMDISP on functional profiles:\n")
print(perm_disp)

cat("\nMean functional richness per environment:\n")
for(env in levels(metadata_matched$Environment)) {
  env_samples <- metadata_matched$Sample[metadata_matched$Environment == env]
  env_samples <- intersect(env_samples, colnames(faprotax_final))
  richness    <- apply(faprotax_final[, env_samples, drop = FALSE], 2,
                       function(x) sum(x > 0))
  cat(sprintf("  %s: %.1f +/- %.1f\n", env, mean(richness), sd(richness)))
}

cat("\nDone. Output files:\n")
cat("  faprotax_4panel_notufts.pdf    -- main 4-panel figure\n")
cat("  faprotax_taxa_functions_notufts.pdf -- taxa driving functions\n")
cat("\nSamples analyzed:", ncol(faprotax_final), "\n")
cat("Functional groups with signal:", nrow(faprotax_final), "\n")

# -----------------------------------------------------------------------------
# 9. BH-CORRECTED KRUSKAL-WALLIS RESULTS FOR ALL PANEL B / C FUNCTIONS
# -----------------------------------------------------------------------------
panel_B_funcs <- c(
  "photosynthetic_cyanobacteria",
  "aerobic_chemoheterotrophy",
  "photoheterotrophy",
  "predatory_or_exoparasitic",
  "nitrate_reduction"
)

panel_C_funcs <- c(
  "intracellular_parasites",
  "fermentation",
  "dark_hydrogen_oxidation",
  "nitrification",
  "manganese_oxidation",
  "aerobic_ammonia_oxidation",
  "chitinolysis",
  "methylotrophy",
  "methanol_oxidation",
  "nitrogen_fixation"
)

all_funcs <- c(panel_B_funcs, panel_C_funcs)
all_funcs <- all_funcs[all_funcs %in% rownames(faprotax_final)]

cat("\n=== BH-CORRECTED KRUSKAL-WALLIS RESULTS (Panel B + C functions) ===\n")

kw_results <- data.frame()
for(func in all_funcs) {
  func_data <- data.frame(
    Abundance   = as.numeric(faprotax_final[func, ]),
    Environment = metadata_matched$Environment
  )
  kw <- kruskal.test(Abundance ~ Environment, data = func_data)
  kw_results <- rbind(kw_results, data.frame(Function = func, p_value = kw$p.value))
}

# BH correction across these 15 pre-selected functions
kw_results$p_adj <- p.adjust(kw_results$p_value, method = "BH")

for(i in seq_len(nrow(kw_results))) {
  func  <- kw_results$Function[i]
  p_adj <- kw_results$p_adj[i]

  if(!is.na(p_adj) && p_adj < 0.05) {
    func_data <- data.frame(
      Abundance   = as.numeric(faprotax_final[func, ]),
      Environment = metadata_matched$Environment
    )
    env_medians <- func_data %>%
      dplyr::group_by(Environment) %>%
      dplyr::summarise(med = median(Abundance), .groups = "drop") %>%
      dplyr::arrange(dplyr::desc(med))
    highest <- as.character(env_medians$Environment[1])
    sig <- ifelse(p_adj < 0.001, "***", ifelse(p_adj < 0.01, "**", "*"))
    cat(sprintf("%-35s p_raw=%.4f p_adj=%.4f %s highest=%s\n",
                func, kw_results$p_value[i], p_adj, sig, highest))
  } else {
    cat(sprintf("%-35s p_raw=%.4f p_adj=%.4f ns\n",
                func, kw_results$p_value[i], p_adj))
  }
}

# -----------------------------------------------------------------------------
# 10. TAXA DRIVING SIGNIFICANT FUNCTIONS PER ENVIRONMENT
# -----------------------------------------------------------------------------
cat("\n=== TAXA DRIVING SIGNIFICANT FUNCTIONS PER ENVIRONMENT ===\n")

input_notufts <- readRDS("bac_input_filt_rare_notufts.rds")
asv_table <- input_notufts$data_loaded
tax_table <- input_notufts$taxonomy_loaded
meta_rds  <- input_notufts$map_loaded

taxa_func_list <- list(
  photosynthetic_cyanobacteria = c(
    "Tychonema_CCAP_1459-11B", "Leptolyngbya_ANT.L67.1",
    "Chamaesiphon_PCC-7430", "Phormidium_CYN64",
    "Phormidesmis_ANT.L52.6", "Pseudanabaena_PCC-7429",
    "Geitlerinema_LD9", "Nodosilinea_PCC-7104",
    "Nostoc_PCC-73102", "Crinalium_SAG_22.89",
    "Synechococcus_PCC-7502", "Scytolyngbya_XSP1"
  ),
  aerobic_chemoheterotrophy = c(
    "Flavobacterium", "Pedobacter", "Sphingomonas",
    "Rhodanobacter", "Cryobacterium", "Nocardioides",
    "Bryobacter", "Galbitalea", "Legionella", "Leptothrix",
    "Roseomonas", "Cytophaga"
  ),
  photoheterotrophy = c(
    "Cereibacter", "Porphyrobacter", "Rhodobacter",
    "Rhodoferax", "Roseococcus", "Sandaracinobacter"
  ),
  predatory_or_exoparasitic = c("Bdellovibrio", "Haliangium"),
  nitrate_reduction         = c("Knoellia", "Opitutus", "Rubrobacter"),
  intracellular_parasites   = c(
    "Candidatus_Gigarickettsia", "Candidatus_Megaira",
    "Candidatus_Protochlamydia", "Coxiella",
    "Legionella", "Neochlamydia", "Rickettsia"
  ),
  nitrification = c(
    "966-1", "Candidatus_Nitrotoga", "Ellin6067",
    "MND1", "Nitrosomonas", "Nitrosospira"
  ),
  aerobic_ammonia_oxidation = c(
    "966-1", "Ellin6067", "MND1", "Nitrosomonas", "Nitrosospira"
  ),
  manganese_oxidation = c("Leptothrix"),
  methylotrophy       = c("Methylobacter", "Methylotenera"),
  methanol_oxidation  = c("Methylotenera"),
  chitinolysis        = c("Lysobacter"),
  nitrogen_fixation   = c("Bradyrhizobium", "Mesorhizobium", "Nostoc_PCC-73102")
)

env_map <- setNames(as.character(metadata_matched$Environment),
                    metadata_matched$Sample)

for(func in names(taxa_func_list)) {
  genera <- taxa_func_list[[func]]
  cat(sprintf("\n%s:\n", func))

  for(env in c("Desiccated", "Pond", "Lake")) {
    env_samples <- names(env_map)[env_map == env]
    env_samples <- intersect(env_samples, colnames(asv_table))
    if(length(env_samples) == 0) next

    env_asv      <- asv_table[, env_samples, drop = FALSE]
    genus_totals <- data.frame()

    for(genus in genera) {
      matching <- tax_table$taxonomy6 == genus
      if(sum(matching) > 0) {
        total <- sum(rowSums(env_asv[matching, , drop = FALSE]))
        if(total > 0) {
          genus_totals <- rbind(genus_totals, data.frame(
            Genus = genus, Reads = total
          ))
        }
      }
    }

    if(nrow(genus_totals) > 0) {
      genus_totals <- genus_totals[order(-genus_totals$Reads), ]
      genus_totals$Pct <- round(genus_totals$Reads /
                                  sum(genus_totals$Reads) * 100, 1)
      cat(sprintf("  %s:\n", env))
      for(i in seq_len(min(5, nrow(genus_totals)))) {
        cat(sprintf("    %-45s %d reads (%s%%)\n",
                    genus_totals$Genus[i],
                    genus_totals$Reads[i],
                    genus_totals$Pct[i]))
      }
    } else {
      cat(sprintf("  %s: no reads found\n", env))
    }
  }
}


# -----------------------------------------------------------------------------
# 11. TAXA DRIVING PHOTOHETEROTROPHY, PREDATORY/EXOPARASITIC ACTIVITY, AND
#     NITRATE REDUCTION -- SUPPLEMENTARY HEATMAP FIGURE
#     Uses the same genus-level read-count data computed in Section 10
#     (taxa_func_list, asv_table, tax_table, env_map), restructured into a
#     plottable data frame instead of only printing to console.
# -----------------------------------------------------------------------------
cat("\nBuilding taxa-driving-function heatmap for photoheterotrophy, ",
    "predatory_or_exoparasitic, nitrate_reduction...\n")

target_funcs <- c("photoheterotrophy", "predatory_or_exoparasitic", "nitrate_reduction")

genus_pct_data <- data.frame()

for (func in target_funcs) {
  genera <- taxa_func_list[[func]]

  for (env in c("Desiccated", "Pond", "Lake")) {
    env_samples <- names(env_map)[env_map == env]
    env_samples <- intersect(env_samples, colnames(asv_table))
    if (length(env_samples) == 0) next

    env_asv <- asv_table[, env_samples, drop = FALSE]
    genus_totals <- data.frame()

    for (genus in genera) {
      matching <- tax_table$taxonomy6 == genus
      if (sum(matching) > 0) {
        total <- sum(rowSums(env_asv[matching, , drop = FALSE]))
        if (total > 0) {
          genus_totals <- rbind(genus_totals, data.frame(Genus = genus, Reads = total))
        }
      }
    }

    if (nrow(genus_totals) > 0) {
      genus_totals$Pct <- genus_totals$Reads / sum(genus_totals$Reads) * 100
      genus_totals$Function    <- func
      genus_totals$Environment <- env
      genus_pct_data <- rbind(genus_pct_data, genus_totals)
    }
  }
}

# Fill in genus/function/environment combinations with no reads as 0, so the
# heatmap grid is complete (matching the style of the other taxa heatmaps)
all_genera_target <- sort(unique(genus_pct_data$Genus))
full_grid_target <- expand.grid(
  Genus       = all_genera_target,
  Function    = target_funcs,
  Environment = factor(env_order, levels = env_order),
  stringsAsFactors = FALSE
)

genus_pct_data <- full_grid_target %>%
  dplyr::left_join(genus_pct_data, by = c("Genus", "Function", "Environment")) %>%
  dplyr::mutate(Pct = ifelse(is.na(Pct), 0, Pct))

# ggplot's discrete y-axis places the FIRST factor level at the bottom
# and the LAST at the top -- so to render top-to-bottom as
# photoheterotrophy / predatory_or_exoparasitic / nitrate_reduction
# (matching target_funcs' own order), the factor levels must be reversed
genus_pct_data$Function    <- factor(genus_pct_data$Function, levels = rev(target_funcs))
genus_pct_data$Environment <- factor(genus_pct_data$Environment, levels = env_order)

global_max_target <- max(genus_pct_data$Pct, na.rm = TRUE)

make_target_heatmap <- function(env_name, fill_high, show_y = TRUE) {
  env_data <- genus_pct_data %>%
    dplyr::filter(Environment == env_name) %>%
    dplyr::mutate(Plot_Pct = ifelse(Pct > 0, Pct, NA))

  ggplot(env_data, aes(x = Genus, y = Function, fill = Plot_Pct)) +
    geom_tile(color = "grey85", linewidth = 0.3) +
    scale_fill_gradient(
      low      = "white",
      high     = fill_high,
      na.value = "white",
      name     = paste0(env_name, "\n% of function\nreads (genus)"),
      limits   = c(0, global_max_target)
    ) +
    theme_minimal(base_size = 10) +
    labs(title = env_name, x = NULL, y = NULL) +
    theme(
      plot.title      = element_text(hjust = 0.5, size = 11, face = "bold", color = fill_high),
      axis.text.x     = element_text(angle = 45, hjust = 1, size = 7.5, face = "bold.italic"),
      axis.text.y     = element_text(size = 8, face = "bold",
                                      color = if (show_y) "black" else "white"),
      panel.grid      = element_blank(),
      legend.position = "right"
    )
}

p_target_desic <- make_target_heatmap("Desiccated", env_colors["Desiccated"], show_y = TRUE)
p_target_pond  <- make_target_heatmap("Pond",        env_colors["Pond"],       show_y = FALSE)
p_target_lake  <- make_target_heatmap("Lake",        env_colors["Lake"],       show_y = FALSE)

plot_F_supp <- (p_target_desic | p_target_pond | p_target_lake) +
  plot_annotation(
    title   = "Taxa Driving Photoheterotrophy, Predatory/Exoparasitic Activity, and Nitrate Reduction",
    caption = "Fill = percentage of that function's total reads (within habitat) contributed by each genus  |  White = genus absent or contributed 0 reads",
    theme   = theme(
      plot.title   = element_text(face = "bold", size = 11, hjust = 0.5),
      plot.caption = element_text(size = 7, hjust = 0.5)
    )
  ) &
  theme(text = element_text(family = "sans", face = "bold"))

ggsave(
  "faprotax_photohetero_predatory_nitrate_taxa_supp_notufts.pdf",
  plot_F_supp,
  width  = 14,
  height = 6,
  dpi    = 300
)
ggsave(
  "faprotax_photohetero_predatory_nitrate_taxa_supp_notufts.jpeg",
  plot_F_supp,
  width   = 14,
  height  = 6,
  dpi     = 300,
  quality = 100
)
cat("Saved: faprotax_photohetero_predatory_nitrate_taxa_supp_notufts.pdf and .jpeg\n")
